# Generated by Django 5.0.6 on 2024-05-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_alter_poem_options_alter_poet_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={'ordering': ['name'], 'verbose_name': '', 'verbose_name_plural': '1. دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='poem',
            options={'ordering': ['id'], 'verbose_name': '', 'verbose_name_plural': '3. اشعار'},
        ),
        migrations.AlterModelOptions(
            name='poet',
            options={'ordering': ['id'], 'verbose_name': '', 'verbose_name_plural': '2. شاعران'},
        ),
        migrations.AlterModelOptions(
            name='verse',
            options={'ordering': ['poem_id', 'vorder'], 'verbose_name': '', 'verbose_name_plural': '4. متن اشعار'},
        ),
        migrations.AlterField(
            model_name='poet',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]