# Generated by Django 5.0.6 on 2024-05-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_alter_cat_options_alter_poem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poet',
            name='name',
            field=models.CharField(max_length=55),
        ),
    ]
